language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-21
  licenses:
      - android-sdk-license-.+

before_install:
  - chmod +x gradlew
  - android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null